name: git-issue-release

on:
  pull_request:
    types: [closed]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: git-issue-release
        uses: hogashi/git-issue-release@v1.0.0-a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release-tag-pattern: ^v
          release-label: "release"
